{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "grandline.fullname" . }}-backend
  labels:
    {{- include "grandline.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    {{- include "grandline.selectorLabels" (dict "ctx" . "component" "backend") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
{{- end }}
